### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by a-ceron** [a-ceron/tesis-ia#10]
# ¿Qué?
Después de entrenar un modelo la memoria del GPU se puede llenar. Al intentar ejecutrar un nuevo entrenamiento el siguiente error aparece

```python
(pytorch) ariel@rumelhart:~/Documents/tesis-ia/lens_effect_project$ python main.py
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    main()
  File "main.py", line 22, in main
    trainer.train(generator, discriminator, dataloader)
  File "/home/ariel/Documents/tesis-ia/lens_effect_project/trainer.py", line 30, in train
    generator.to(device)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory
```

# Cómo 
Se ejecuta el siguiente comando
```linux
nvidia-smi
```

Buscamos el proceso que este usando la memoria, usualmente se llama `python`

```linux
Mon Feb 27 21:21:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 54%   82C    P2   145W / 180W |   7873MiB /  8119MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 27%   30C    P8     6W / 180W |      6MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       967      G   /usr/lib/xorg/Xorg                  8MiB |
|    0   N/A  N/A      1230      G   /usr/bin/gnome-shell                2MiB |
|    0   N/A  N/A    924757      C   python                           7857MiB |
|    1   N/A  N/A       967      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

Después de haber identificado el proceso, se elimina para liberar la memoria
```linux
sudo kill -9 {PID}
```

Esta acción requiere a un usuario con privilegios para ser ejecutada.

[Enlace original](https://stackoverflow.com/questions/54374935/how-to-fix-this-strange-error-runtimeerror-cuda-error-out-of-memory)

**Comment by a-ceron** [comment]
# Solución 1.
De forma temporal voy a usar el CPU en vez del GPU. 

# Solución 2.
La solución definitiva debe ser eliminar el proceso y evitar que se vuelva a llenar la memoria.

**Comment by a-ceron** [comment]
# Resultados usando GPU
## Resultados con los datos de Pedro

![830](https://user-images.githubusercontent.com/40130391/221756825-f526b01e-3456-48fb-8c76-06d009832749.png)
![704](https://user-images.githubusercontent.com/40130391/221756835-8be82252-5ddb-4e13-ba53-f23d9040a71e.png)

Hay una mejora en los resultados observados
![Captura de pantalla 2023-02-27 a la(s) 22 49 24](https://user-images.githubusercontent.com/40130391/221756947-a64daf81-fb8c-4bcb-89df-04207aa44e14.png)

## Resultados con los datos descargados
![93](https://user-images.githubusercontent.com/40130391/221757581-28ddcbf2-d890-4905-a249-5ecd4de42e01.png)

El entrenamiento para estos datos siguen teniendo un comportamiento extraño
![Captura de pantalla 2023-02-27 a la(s) 22 54 20](https://user-images.githubusercontent.com/40130391/221757641-2952e922-907e-45f5-9c26-ab748baac40d.png)

**Comment by a-ceron** [comment]
![Captura de pantalla 2023-02-28 a la(s) 23 21 17](https://user-images.githubusercontent.com/40130391/222052107-f8ea0aea-6350-4588-983a-9c720ed10a44.png)
![208](https://user-images.githubusercontent.com/40130391/222052171-ad028372-4cc7-4293-a732-4ab2895884b8.png)
