### ISSUE TITLE
Runtimerror

### ISSUE THREAD

**Issue by a-ceron** [a-ceron/tesis-ia#37]
# Qué
Se hizo una modificación al codigo GAN para probar la transferencia de conocimiento con el minerGAN. El entrenamiento hecho con esta red no termino satisfactoriamente porque aparecio el siguiente error
```python
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    main()
  File "main.py", line 116, in main
    train_and_test_simple_gan()
  File "main.py", line 56, in train_and_test_simple_gan
    trainer.train()
  File "/home/ariel/Documents/tesis-ia/lens_effect_project/app/model/trainers.py", line 250, in train
    # Optimización de los modelos
  File "/home/ariel/Documents/tesis-ia/lens_effect_project/app/model/utils/tools.py", line 25, in plot_batch
    gen_batch = generator(noise).detach().cpu()
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ariel/Documents/tesis-ia/lens_effect_project/app/model/GANs/aGAN.py", line 136, in forward
    return self.model(X)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 958, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: Given transposed=1, weight of size [100, 1024, 4, 4], expected input[64, 16, 1, 1] to have 100 channels, but got 16 channels instead
```

# Pasos para replicar el error
Correr una entrameinto con el modelo aGAN

# Resultado esperado
Que el modelo termine de entrenar sin error alguno

**Comment by a-ceron** [comment]
Había un error en las dimensiones del modelo. Se hizo un debug del código y se encontró los parámetros que hacian este error.
